#!/bin/sh

../bin-${OSTYPE}/pascal -I.. $*

# First, just dump the table without executing
../bin-${OSTYPE}/sm -d a.out

# Now execute
#./bin-${OSTYPE}/sm a.out | tee a.log
../bin-${OSTYPE}/jit a.out
