#define SSL_CODE_TABLE_SIZE 3400

#define oJumpForward 0
#define oJumpBack 1
#define oInput 2
#define oInputAny 3
#define oEmit 4
#define oError 5
#define oInputChoice 6
#define oCall 7
#define oReturn 8
#define oSetResult 9
#define oChoice 10
#define oEndChoice 11
#define oPushResult 12
#define oPop 13
#define oBreak 14
#define oGlobalSpace 15
#define oLocalSpace 16
#define oGetParam 17
#define oGetFromParam 18
#define oGetLocal 19
#define oGetGlobal 20
#define oGetAddrParam 21
#define oGetAddrLocal 22
#define oGetAddrGlobal 23
#define oAssign 24
#define pIdent 0
#define pIntLit 1
#define pStrLit 2
#define pAssign 3
#define pSemiColon 4
#define pEqual 5
#define pNotEqual 6
#define pLess 7
#define pGreater 8
#define pLessEqual 9
#define pGreaterEqual 10
#define pColon 11
#define pComma 12
#define pLParen 13
#define pRParen 14
#define pLSquare 15
#define pRSquare 16
#define pCarat 17
#define pDot 18
#define pDotDot 19
#define pTimes 20
#define pDivide 21
#define pPlus 22
#define pMinus 23
#define pEof 24
#define pInvalid 25
#define pProgram 26
#define pProcedure 27
#define pFunction 28
#define pConst 29
#define pType 30
#define pVar 31
#define pBegin 32
#define pEnd 33
#define pArray 34
#define pRecord 35
#define pSet 36
#define pOf 37
#define pIf 38
#define pThen 39
#define pElse 40
#define pFor 41
#define pTo 42
#define pDownto 43
#define pDo 44
#define pWhile 45
#define pRepeat 46
#define pUntil 47
#define pCycle 48
#define pExit 49
#define pReturn 50
#define pAnd 51
#define pOr 52
#define pNot 53
#define pWriteln 54
#define pWrite 55
#define pReadln 56
#define pRead 57
#define tPushIntVar 0
#define tPushBoolVar 1
#define tPushPtrVar 2
#define tPushAddr 3
#define tFetchInt 4
#define tFetchBool 5
#define tFetchPtr 6
#define tPushIntLit 7
#define tAssignInt 8
#define tAssignBool 9
#define tAssignPtr 10
#define tCopy 11
#define tIncIntVar 12
#define tDecIntVar 13
#define tMultiplyInt 14
#define tDivideInt 15
#define tAddInt 16
#define tSubtractInt 17
#define tNegateInt 18
#define tNot 19
#define tAnd 20
#define tOr 21
#define tEqualInt 22
#define tNotEqualInt 23
#define tGreaterInt 24
#define tLessInt 25
#define tGreaterEqualInt 26
#define tLessEqualInt 27
#define tEqualPtr 28
#define tNotEqualPtr 29
#define tCall 30
#define tReturn 31
#define tJump 32
#define tJumpTrue 33
#define tJumpFalse 34
#define tPutInt 35
#define tPutBool 36
#define tPutStr 37
#define tPutPtr 38
#define tPutCR 39
#define tSpace 40
#define tConstant 41
#define tSymVal 42
#define eBadStatement 0
#define eNotConst 1
#define eNotType 2
#define eNotVar 3
#define eNotIntVar 4
#define eNotValue 5
#define eNotInteger 6
#define eNotBoolean 7
#define eNotPointer 8
#define eNotArray 9
#define eTooManySubscripts 10
#define eTypeMismatch 11
#define eNotImplemented 12
#define eNotAllowed 13
#define eNotInALoop 14
#define eRecordEmpty 15
#define nINVALID 0
#define Object 1
#define nScope 2
#define nDeclaration 3
#define nIdent 4
#define nProgram 5
#define nProc 6
#define nFunc 7
#define nConst 8
#define nTypeDecl 9
#define nVar 10
#define nGlobalVar 11
#define nLocalVar 12
#define nRecordField 13
#define nParam 14
#define nType 15
#define nFileType 16
#define nIntegerType 17
#define nBooleanType 18
#define nCharType 19
#define nStringType 20
#define nPointerType 21
#define nArrayType 22
#define nSubrangeType 23
#define nRecordType 24
#define nEnumType 25
#define nSetType 26
#define qINVALID 0
#define qParentScope 1
#define qDecls 2
#define qNextOffset 3
#define qIdent 4
#define qKind 5
#define qType 6
#define qParamType 7
#define qValue 8
#define qParams 9
#define qChildScope 10
#define qInOut 11
#define qSize 12
#define qPointerType 13
#define qBaseType 14
#define qIndexType 15
#define qLow 16
#define qHigh 17
#define qScope 18
#define Null 0
#define NullVec 0
#define false 0
#define true 1
#define zero 0
#define one 1
#define kUndefined 0
#define kProgram 1
#define kProc 2
#define kFunc 3
#define kConst 4
#define kType 5
#define kVar 6
#define tyNone 0
#define tyInteger 1
#define tyBoolean 2
#define tyChar 3
#define tyString 4
#define tyFile 5
#define tyPointer 6
#define tyArray 7
#define tyRecord 8
#define tyParams 9
#define tySet 10
#define oNodeNew 25
#define oNodeSet 26
#define oNodeSetInt 27
#define oNodeSetBoolean 28
#define oNodeSetKind 29
#define oNodeGet 30
#define oNodeGetInt 31
#define oNodeGetBoolean 32
#define oNodeNull 33
#define oNodeNext 34
#define oNodeType 35
#define oNodeEqual 36
#define oNodeVecNew 37
#define oNodeVecDelete 38
#define oNodeVecAppend 39
#define oNodeVecSize 40
#define oNodeVecElement 41
#define inc 42
#define dec 43
#define negate 44
#define subtract 45
#define multiply 46
#define equal 47
#define equal_zero 48
#define equal_node_type 49
#define TOKEN_VALUE 50
#define LAST_ID 51
#define oScopeBegin 52
#define oScopeEnd 53
#define oScopeCurrent 54
#define oScopeDeclare 55
#define oScopeDeclareAlloc 56
#define oScopeFind 57
#define oScopeFindRequire 58
#define oTypeAdd 59
#define oIdAdd_File 60
#define oIdAdd_Integer 61
#define oIdAdd_Boolean 62
#define oIdAdd_Char 63
#define oIdAdd_String 64
#define oIdAdd_True 65
#define oIdAdd_False 66
#define oCountPush 67
#define oCountInc 68
#define oCountDec 69
#define oCountIsZero 70
#define oCountPop 71
#define oSymPushLevel 72
#define oSymPopLevel 73
#define oSymPopLevelSaveType 74
#define oSymLookup 75
#define oSymChooseKind 76
#define oSymAddSPop 77
#define oSymLevelAnySyms 78
#define oSymSPushId 79
#define oSymSSetKind 80
#define oSymSSetValPop 81
#define oSymSSetTypS 82
#define oSymSSetParamTypS 83
#define oSymSAllocate 84
#define oValuePushToken 85
#define oValuePushVal 86
#define oValuePush 87
#define oValuePushSizeTS 88
#define oValuePushLowTS 89
#define oValueNegate 90
#define oValueDifference 91
#define oValueMultiply 92
#define oValueIsZero 93
#define oValueIsOne 94
#define oValueTop 95
#define oValuePop 96
#define oStringAllocLit 97
#define oTypSPushTyp 98
#define oTypSPush 99
#define oTypSPopPushBase 100
#define oTypSPopPushPtr 101
#define oTypSMatch 102
#define oTypSChoose 103
#define oTypSChoosePop 104
#define oTypSChooseKind 105
#define oTypSChoosePtr 106
#define oTypSSwap 107
#define oTypSPop 108
#define oTypNew 109
#define oTypSetLow 110
#define oTypSetHigh 111
#define oTypSetSize 112
#define oTypAssignBasePop 113
#define oTypAssignPtr 114
#define patchLoop 0
#define patchExit 1
#define patchIf 2
#define oPatchPushHere 115
#define oPatchAnyEntries 116
#define oPatchSwap 117
#define oPatchDup 118
#define oPatchPopFwd 119
#define oPatchPopBack 120

#ifdef SSL_INCLUDE_ERR_TABLE

struct ssl_error_table_struct ssl_error_table[] = {
   "eBadStatement", 0,
   "eNotConst", 1,
   "eNotType", 2,
   "eNotVar", 3,
   "eNotIntVar", 4,
   "eNotValue", 5,
   "eNotInteger", 6,
   "eNotBoolean", 7,
   "eNotPointer", 8,
   "eNotArray", 9,
   "eTooManySubscripts", 10,
   "eTypeMismatch", 11,
   "eNotImplemented", 12,
   "eNotAllowed", 13,
   "eNotInALoop", 14,
   "eRecordEmpty", 15,
   "", 0
};
int ssl_error_table_size = 16;

#endif // SSL_INCLUDE_ERR_TABLE
