#define SSL_CODE_TABLE_SIZE 14800

#define oJumpForward 0
#define oJumpBack 1
#define oInput 2
#define oInputAny 3
#define oEmit 4
#define oError 5
#define oInputChoice 6
#define oCall 7
#define oReturn 8
#define oSetResult 9
#define oChoice 10
#define oEndChoice 11
#define oPushResult 12
#define oPop 13
#define oBreak 14
#define oGlobalSpace 15
#define oLocalSpace 16
#define oGetParam 17
#define oGetFromParam 18
#define oGetLocal 19
#define oGetGlobal 20
#define oGetAddrParam 21
#define oGetAddrLocal 22
#define oGetAddrGlobal 23
#define oAssign 24
#define pIdent 0
#define pIntLit 1
#define pStrLit 2
#define pCharLit 3
#define pAssign 4
#define pSemiColon 5
#define pEqual 6
#define pNotEqual 7
#define pLess 8
#define pGreater 9
#define pLessEqual 10
#define pGreaterEqual 11
#define pColon 12
#define pComma 13
#define pLParen 14
#define pRParen 15
#define pLSquare 16
#define pRSquare 17
#define pCarat 18
#define pAt 19
#define pDot 20
#define pDotDot 21
#define pTimes 22
#define pDivide 23
#define pPlus 24
#define pMinus 25
#define pEof 26
#define pInvalid 27
#define pProgram 28
#define pProcedure 29
#define pFunction 30
#define pConst 31
#define pType 32
#define pVar 33
#define pLabel 34
#define pBegin 35
#define pEnd 36
#define pArray 37
#define pRecord 38
#define pSet 39
#define pOf 40
#define pIf 41
#define pThen 42
#define pElse 43
#define pFor 44
#define pTo 45
#define pDownto 46
#define pDo 47
#define pWhile 48
#define pRepeat 49
#define pUntil 50
#define pContinue 51
#define pBreak 52
#define pCase 53
#define pOtherwise 54
#define pGoto 55
#define pAnd 56
#define pOr 57
#define pNot 58
#define pUses 59
#define pUnit 60
#define pInterface 61
#define pImplementation 62
#define pInitialization 63
#define pFinalization 64
#define pWriteln 65
#define pWrite 66
#define pReadln 67
#define pRead 68
#define pForward 69
#define pExternal 70
#define pName 71
#define pCdecl 72
#define tPushGlobalI 0
#define tPushGlobalB 1
#define tPushGlobalP 2
#define tPushLocalI 3
#define tPushLocalB 4
#define tPushLocalP 5
#define tPushParamI 6
#define tPushParamB 7
#define tPushParamP 8
#define tPushUpLocalI 9
#define tPushUpLocalB 10
#define tPushUpLocalP 11
#define tPushUpParamI 12
#define tPushUpParamB 13
#define tPushUpParamP 14
#define tPushConstI 15
#define tPushAddrGlobal 16
#define tPushAddrLocal 17
#define tPushAddrParam 18
#define tPushAddrActual 19
#define tPushAddrUpLocal 20
#define tPushAddrUpParam 21
#define tSwap 22
#define tFetchI 23
#define tFetchB 24
#define tFetchP 25
#define tAssignI 26
#define tAssignB 27
#define tAssignP 28
#define tCopy 29
#define tCastBtoI 30
#define tCastItoB 31
#define tIncI 32
#define tDecI 33
#define tMultI 34
#define tDivI 35
#define tAddPI 36
#define tAddI 37
#define tSubP 38
#define tSubPI 39
#define tSubI 40
#define tNegI 41
#define tNot 42
#define tEqualB 43
#define tNotEqualB 44
#define tGreaterB 45
#define tLessB 46
#define tGreaterEqualB 47
#define tLessEqualB 48
#define tEqualI 49
#define tNotEqualI 50
#define tGreaterI 51
#define tLessI 52
#define tGreaterEqualI 53
#define tLessEqualI 54
#define tEqualP 55
#define tNotEqualP 56
#define tGreaterP 57
#define tLessP 58
#define tGreaterEqualP 59
#define tLessEqualP 60
#define tAllocActuals 61
#define tAllocActualsCdecl 62
#define tFreeActuals 63
#define tCall 64
#define tCallCdecl 65
#define tReturn 66
#define tEnter 67
#define tJump 68
#define tJumpTrue 69
#define tJumpFalse 70
#define tJumpCaseB 71
#define tJumpCaseI 72
#define tJumpCaseS 73
#define tCase 74
#define tCaseRange 75
#define tCaseEnd 76
#define tLabel 77
#define tLabelAlias 78
#define tLabelExtern 79
#define tWriteI 80
#define tWriteBool 81
#define tWriteChar 82
#define tWriteShortStr 83
#define tWritePChar 84
#define tWriteP 85
#define tWriteEnum 86
#define tWriteCR 87
#define tReadI 88
#define tReadChar 89
#define tReadShortStr 90
#define tReadCR 91
#define tFile 92
#define tLine 93
#define tSpace 94
#define eBadStatement 0
#define eNotConst 1
#define eNotType 2
#define eNotOrdinalType 3
#define eNotVar 4
#define eNotIntVar 5
#define eNotValue 6
#define eNotInteger 7
#define eNotBoolean 8
#define eNotPointer 9
#define eNotArray 10
#define eNotRecord 11
#define eNotRecordField 12
#define eTooManySubscripts 13
#define eTypeMismatch 14
#define eMissingParameter 15
#define eNotImplemented 16
#define eNotAllowed 17
#define eNotInALoop 18
#define eRecordEmpty 19
#define eNotCurrentFunction 20
#define eAlreadyDefined 21
#define eOnlyOneVarCanBeInitialized 22
#define eExternalMethodCannotBeNested 23
#define eCantFindUnitFile 24
#define eInternalScopeMismatch 25
#define eEnumValueNotAscending 26
#define eUsedButNotDefined 27
#define eCantUsePredSuccOnEnumWithValueGaps 28
#define eCantDereference 29
#define eSizeMismatch 30
#define eTypeNameNotAllowedHere 31
#define nINVALID 0
#define Object 1
#define nWorkspace 2
#define nModule 3
#define nProgram 4
#define nUnit 5
#define nUnitImpl 6
#define nScope 7
#define nDeclaration 8
#define nIdent 9
#define nUnitRef 10
#define nMethod 11
#define nProc 12
#define nFunc 13
#define nBuiltInFunc 14
#define nBuiltInProc 15
#define nConst 16
#define nEnumValue 17
#define nConstStr 18
#define nTypeDecl 19
#define nVar 20
#define nGlobalVar 21
#define nLocalVar 22
#define nRecordField 23
#define nParam 24
#define nTypedConst 25
#define nLabel 26
#define nType 27
#define nFileType 28
#define nIntegerType 29
#define nByteType 30
#define nBooleanType 31
#define nBooleanFlowType 32
#define nCharType 33
#define nPointerType 34
#define nUniversalPointerType 35
#define nArrayType 36
#define nSubrangeType 37
#define nRecordType 38
#define nStrLitType 39
#define nShortStringType 40
#define nEnumType 41
#define nSetType 42
#define qINVALID 0
#define qUnits 1
#define qProgram 2
#define qGlobalSize 3
#define qIdent 4
#define qUsedUnits 5
#define qChildScope 6
#define qMainRoutineScope 7
#define qImpl 8
#define qPublicScope 9
#define qPrivateScope 10
#define qInitLabel 11
#define qFinalLabel 12
#define qInitRoutineScope 13
#define qLevel 14
#define qDecls 15
#define qExtends 16
#define qSize 17
#define qAllocMode 18
#define qInitCode 19
#define qParentScope 20
#define qType 21
#define qValue 22
#define qParams 23
#define qBodyDefined 24
#define qExternal 25
#define qExternalName 26
#define qCdecl 27
#define qUsed 28
#define qOldParams 29
#define qOldType 30
#define qResultOffset 31
#define qNameOffset 32
#define qValueStr 33
#define qInOut 34
#define qDefined 35
#define qPointerType 36
#define qBaseType 37
#define qIndexType 38
#define qLow 39
#define qHigh 40
#define qScope 41
#define qCapacity 42
#define qNameTable 43
#define qHasGap 44
#define Null 0
#define NullIter 0
#define NullVec 0
#define false 0
#define true 1
#define tyNone 0
#define tyInteger 1
#define tyBoolean 2
#define tyChar 3
#define tyString 4
#define tyFile 5
#define tyPointer 6
#define tyArray 7
#define tyRecord 8
#define tyParams 9
#define tySet 10
#define labelNull 0
#define codeNull 0
#define codeDefault 1
#define stringNull 0
#define allocGlobal 0
#define allocDown 1
#define allocUp 2
#define oNodeNew 25
#define oNodeSet 26
#define oNodeSetString 27
#define oNodeSetInt 28
#define oNodeSetBoolean 29
#define oNodeSetLabel 30
#define oNodeSetCode 31
#define oNodeAddLast 32
#define oNodeGet 33
#define oNodeGetString 34
#define oNodeGetInt 35
#define oNodeGetBoolean 36
#define oNodeGetLabel 37
#define oNodeGetCode 38
#define oNodeNull 39
#define oNodeFind 40
#define oNodeGetIter 41
#define oNodeGetIterLast 42
#define oNodeIterValue 43
#define oNodeIterNext 44
#define oNodeIterPrev 45
#define oNodeType 46
#define oNodeEqual 47
#define oNodeVecNew 48
#define oNodeVecDelete 49
#define oNodeVecAppend 50
#define oNodeVecSize 51
#define oNodeVecElement 52
#define oEmitInt 53
#define oEmitLabel 54
#define oEmitCode 55
#define Here 56
#define oPatch 57
#define inc 58
#define dec 59
#define negate 60
#define add 61
#define subtract 62
#define multiply 63
#define equal 64
#define equal_zero 65
#define equal_node 66
#define equal_string 67
#define equal_node_type 68
#define equal_label 69
#define equal_code 70
#define greater 71
#define oMININT 72
#define oMAXINT 73
#define TOKEN_VALUE 74
#define LAST_ID 75
#define ID_STRING 76
#define CURRENT_STRLIT 77
#define UNACCEPT_TOKEN 78
#define oWorkspaceNew 79
#define oScopeBegin 80
#define oScopeEnter 81
#define oScopeEnd 82
#define oScopeCurrent 83
#define oScopeDeclare 84
#define oScopeDeclareAlloc 85
#define oScopeAllocType 86
#define oScopeAlloc 87
#define oScopeFind 88
#define oScopeFindRequire 89
#define oScopeFindInCurrentScope 90
#define oScopeFindRequireInScope 91
#define oTypeAdd 92
#define oTypeSPush 93
#define oTypeSPop 94
#define oTypeSTop 95
#define oTypeSNodeType 96
#define oId_mysystem 97
#define oId_ShortStringAppendShortString 98
#define oId_ShortStringAppendChar 99
#define oId_ShortStringCmp 100
#define oId_File 101
#define oId_Integer 102
#define oId_Boolean 103
#define oId_Char 104
#define oId_Byte 105
#define oId_Pointer 106
#define oId_ShortString 107
#define oId_True 108
#define oId_False 109
#define oId_Nil 110
#define oId_Ord 111
#define oId_Chr 112
#define oId_Pred 113
#define oId_Succ 114
#define oId_Sizeof 115
#define oChangeIntLitToLabelIdent 116
#define oLabelNew 117
#define oCodeNew 118
#define oCodePush 119
#define oCodePop 120
#define oCodeDiscard 121
#define oIncludeUnitFile 122
#define oIncludeEnd 123
#define oCountPush 124
#define oCountInc 125
#define oCountDec 126
#define oCountIsZero 127
#define oCountPop 128
#define oValuePush 129
#define oValuePushString 130
#define oValueTop 131
#define oValueTopString 132
#define oValueSwap 133
#define oValuePop 134
#define oValueCharToString 135
#define oValueNegate 136
#define oValueEqual 137
#define oValueNotEqual 138
#define oValueLess 139
#define oValueGreater 140
#define oValueLessEqual 141
#define oValueGreaterEqual 142
#define oValueOr 143
#define oValueAnd 144
#define oValueNot 145
#define oValueAdd 146
#define oValueSub 147
#define oValueMult 148
#define oValueDiv 149
#define oValueStringCmp 150
#define oValueStringConcat 151
#define oStringAllocLit 152
#define oStringAllocShortStringLit 153
#define oLoopPush 154
#define oLoopContinueLabel 155
#define oLoopBreakLabel 156
#define oLoopPop 157
#define oMsg 158
#define oMsgTrace 159
#define oMsgNode 160
#define oMsgNodeLong 161
#define oMsgNodeVec 162

#ifdef SSL_INCLUDE_ERR_TABLE

struct ssl_error_table_struct ssl_error_table[] = {
   "eBadStatement", 0,
   "eNotConst", 1,
   "eNotType", 2,
   "eNotOrdinalType", 3,
   "eNotVar", 4,
   "eNotIntVar", 5,
   "eNotValue", 6,
   "eNotInteger", 7,
   "eNotBoolean", 8,
   "eNotPointer", 9,
   "eNotArray", 10,
   "eNotRecord", 11,
   "eNotRecordField", 12,
   "eTooManySubscripts", 13,
   "eTypeMismatch", 14,
   "eMissingParameter", 15,
   "eNotImplemented", 16,
   "eNotAllowed", 17,
   "eNotInALoop", 18,
   "eRecordEmpty", 19,
   "eNotCurrentFunction", 20,
   "eAlreadyDefined", 21,
   "eOnlyOneVarCanBeInitialized", 22,
   "eExternalMethodCannotBeNested", 23,
   "eCantFindUnitFile", 24,
   "eInternalScopeMismatch", 25,
   "eEnumValueNotAscending", 26,
   "eUsedButNotDefined", 27,
   "eCantUsePredSuccOnEnumWithValueGaps", 28,
   "eCantDereference", 29,
   "eSizeMismatch", 30,
   "eTypeNameNotAllowedHere", 31,
   "", 0
};
int ssl_error_table_size = 32;

#endif // SSL_INCLUDE_ERR_TABLE
