/*

  StackMachine.c

               This executes the intermediate t-code generated by
               my Pascal compiler.

  HISTORY
    21Sep89    1st version, runs test.pas
    24Sep89    Pointer instructions
    28Sep89    -dump will dump a readable t-code file
    01Jan90    read string literals into data segment

*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>

#ifdef AMIGA
#include <dos.h>
#endif // AMIGA

#include "pascal.h"

FILE *src,*dmp;

#define codeMax 10000
short code[codeMax],pc;      /* Program memory */
short codeWords;             /* Actual #words used */

#define stackMax 2000
short stack[stackMax],sp;    /* Call stack */

// good grief, can't hardcode these
#define dataMax 40000
short data[dataMax];         /* Data memory */

short temp, *ptr1, *ptr2;
char trace, underflow, dump;


// Forward declarations
void walkTable();
void dumpTable();
void hitBreak();
void fatal( char* msg );
void cleanup();


void
main(argc,argv)
int argc;
char *argv[];
{
  int temp;                /* I can't seem to read a 'short' */
  short arg;
  short address,count;

  trace = 0;

  /* Prepare Files */

  arg = 1;
  if (arg>=argc) {
    printf("Usage:  stackmachine -trace -underflow -dump <file>\n");
    exit(-1);
  }
  while (argv[arg][0]=='-') {
    if (argv[arg][1]=='t' || argv[arg][1]=='T')
      trace = 1;
    else if (argv[arg][1]=='u' || argv[arg][1]=='U')
      underflow = 1;
    else if (argv[arg][1]=='d' || argv[arg][1]=='D')
      dump = 1;
    arg++;
  }
  if((src=fopen(argv[arg],"r"))==NULL) {
    printf("Can't open program file %s\n",argv[arg]);
    exit(-1);
  }
  int read = fscanf(src,"%d",&temp);
  assert( read == 1 );
  codeWords = temp;
  if (codeWords >= codeMax) {
    printf("Program code too big for buffer\n");
    exit(-1);
  }
  printf("Stack Machine ");
  for (pc=0; pc<codeWords; pc++) {
    read = fscanf(src,"%d",&temp);
    assert( read == 1 );
    code[pc] = temp;
  } 

  /* Also get any string literals, and store in data segemnt */
  /* File format: <addr> <#words> <data words>               */

  while (fscanf(src,"%d",&temp) != EOF) {
    address = temp;
    read = fscanf(src,"%d",&temp);
    assert( read == 1 );
    count = temp;
    while (count--) {
      read = fscanf(src,"%d",&temp);
      assert( read == 1 );
      data[address++] = temp;
    }
  }

  fclose(src);
  printf("- program loaded (%d words)\n",codeWords);

#ifdef AMIGA
  onbreak(&hitBreak);
#endif // AMIGA

  if (dump) {
    dumpTable();
    exit(0);
  }

  /* Execute code */

  pc = 0;                        /* Initialize walker */
  sp = 0;

  walkTable();

  printf(".Done\n");
  cleanup();
}


void
walkTable()
{

   while (1) {

     if (trace) printf("[%d]",pc);
     if (underflow)
       if (sp<0) fatal("+++Stack Underflow+++");

     switch (code[pc++]) {

       case tPushGlobalI :
              if (++sp>=stackMax) fatal("stack overflow");
              stack[sp] = data[code[pc++]];
              continue;
       case tPushGlobalB :
              if (++sp>=stackMax) fatal("stack overflow");
              stack[sp] = data[code[pc++]];
              continue;
       case tPushGlobalP :
              if (++sp>=stackMax) fatal("stack overflow");
              stack[sp] = data[code[pc++]];
              continue;
       case tPushConstI :
              if (++sp>=stackMax) fatal("stack overflow");
              stack[sp] = code[pc++];
              continue;
       case tPushConstP :
              if (++sp>=stackMax) fatal("stack overflow");
              stack[sp] = code[pc++];
              continue;
       case tFetchI :
              stack[sp] = data[stack[sp]];
              continue;
       case tFetchB :
              stack[sp] = data[stack[sp]];
              continue;
       case tFetchP :
              stack[sp] = data[stack[sp]];
              continue;
       case tAssignI :
              data[stack[sp-1]] = stack[sp];
              sp -= 2;
              continue;
       case tAssignB :
              data[stack[sp-1]] = stack[sp];
              sp -= 2;
              continue;
       case tAssignP :
              data[stack[sp-1]] = stack[sp];
              sp -= 2;
              continue;
       case tCopy :
              ptr1 = &data[stack[sp-1]];
              ptr2 = &data[stack[sp]];
              for (temp=0; temp<code[pc]; temp++)
                *ptr1++ = *ptr2++;
              sp -= 2;
              pc++;
              continue;
       case tIncGlobalI :
              data[code[pc++]]++;
              continue;
       case tDecGlobalI :
              data[code[pc++]]--;
              continue;
       case tMultI :
              stack[sp-1] *= stack[sp];
              sp--;
              continue;
       case tDivI :
              stack[sp-1] /= stack[sp];
              sp--;
              continue;
       case tAddI :
              stack[sp-1] += stack[sp];
              sp--;
              continue;
       case tSubI :
              stack[sp-1] -= stack[sp];
              sp--;
              continue;
       case tNegI :
              stack[sp] *= -1;
              continue;
       case tNot :
              stack[sp] = !stack[sp];
              continue;
       case tAnd :
              stack[sp-1] = stack[sp-1] && stack[sp];
              sp--;
              continue;
       case tOr :
              stack[sp-1] = stack[sp-1] || stack[sp];
              sp--;
              continue;
       case tEqualI :
              stack[sp-1] = stack[sp-1] == stack[sp];
              sp--;
              continue;
       case tNotEqualI :
              stack[sp-1] = stack[sp-1] != stack[sp];
              sp--;
              continue;
       case tGreaterI :
              stack[sp-1] = stack[sp-1] > stack[sp];
              sp--;
              continue;
       case tLessI :
              stack[sp-1] = stack[sp-1] < stack[sp];
              sp--;
              continue;
       case tGreaterEqualI :
              stack[sp-1] = stack[sp-1] >= stack[sp];
              sp--;
              continue;
       case tLessEqualI :
              stack[sp-1] = stack[sp-1] <= stack[sp];
              sp--;
              continue;
       case tEqualP :
              stack[sp-1] = stack[sp-1] == stack[sp];
              sp--;
              continue;
       case tNotEqualP :
              stack[sp-1] = stack[sp-1] != stack[sp];
              sp--;
              continue;
       case tCall :
              if (++sp==stackMax) fatal("call stack overflow");
              stack[sp] = pc+1;
              pc = code[pc];
              continue;
       case tReturn :
              if (sp) {
                pc = stack[sp--];
                continue;
              } else
                return;            /* done program table */
       case tJump :
              pc = code[pc];
              continue;
       case tJumpTrue :
              if (stack[sp--]) {
                pc = code[pc];
                continue;
              }
              pc++;
              continue;
       case tJumpFalse :
              if (!stack[sp--]) {
                pc = code[pc];
                continue;
              }
              pc++;
              continue;
       case tWriteI :
              printf("%d",stack[sp--]);
              continue;
       case tWriteBool :
              printf(stack[sp--] ? "TRUE" : "FALSE");
              continue;
       case tWriteStr :
              // SARICE 9/26/2021 - string literals are stored in the intermediate file
              //   as pairs of characters in a short, so have an endian problem.
              printf("%s",(char*)&data[stack[sp--]]);
              continue;
       case tWriteP :
              printf(" <%d>",stack[sp--]);
              continue;
       case tWriteCR :
              printf("\n");
              continue;

       default:
              pc--;
              fatal("bad instruction");
     } /* switch */
   }
}


#define op0(str) { fprintf(dmp,"%s\n",str); continue; }
#define op1(str) { fprintf(dmp,"%s\t%4d\n",str,code[pc++]); continue; }

void
dumpTable()
{
  if((dmp=fopen("a.dmp","w"))==NULL) {
    printf("Can't open dump file a.dmp\n");
    exit(5);
  }

   pc = 0;
   while (pc < codeWords) {
     fprintf(dmp,"%4d\t",pc);
     switch (code[pc++]) {
       case tPushGlobalI :   op1("tPushGlobalI");
       case tPushGlobalB :   op1("tPushGlobalB"); 
       case tPushGlobalP :   op1("tPushGlobalP");
       case tPushConstI :    op1("tPushConstI");
       case tPushConstP :    op1("tPushConstP");
       case tFetchI :        op0("tFetchI");
       case tFetchB :        op0("tFetchB");
       case tFetchP :        op0("tFetchP");
       case tAssignI :       op0("tAssignI");
       case tAssignB :       op0("tAssignB");
       case tAssignP :       op0("tAssignP");
       case tCopy :          op1("tCopy   ");
       case tIncGlobalI :    op1("tIncGlobalI");
       case tDecGlobalI :    op1("tDecGlobalI");
       case tMultI :         op0("tMultI");
       case tDivI :          op0("tDivI");
       case tAddI :          op0("tAddI");
       case tSubI :          op0("tSubI");
       case tNegI :          op0("tNegI");
       case tNot :           op0("tNot");
       case tAnd :           op0("tAnd");
       case tOr :            op0("tOr");
       case tEqualI :        op0("tEqualI");
       case tNotEqualI :     op0("tNotEqualI");
       case tGreaterI   :    op0("tGreaterI");
       case tLessI :         op0("tLessI");
       case tGreaterEqualI : op0("tGreaterEqualI");
       case tLessEqualI :    op0("tLessEqualI");
       case tEqualP :        op0("tEqualP");
       case tNotEqualP :     op0("tNotEqualP");
       case tCall :          op1("tCall   ");
       case tReturn :        op0("tReturn");
       case tJump :          op1("tJump   ");
       case tJumpTrue :      op1("tJumpTrue");
       case tJumpFalse :     op1("tJumpFalse");
       case tWriteI :        op0("tWriteI");
       case tWriteBool :     op0("tWriteBool");
       case tWriteStr :      op0("tWriteStr");
       case tWriteP :        op0("tWriteP");
       case tWriteCR :       op0("tWriteCR");
       default :             op0("???");
     }
   }
}


void
hitBreak()
{
  printf(".Breaking...\n");
  cleanup();
  //return(1);
  exit(1);
}


void
fatal( char* msg )
{
  printf(".FATAL - %s at %d\n",msg,pc);
  exit(5);
}


void
cleanup()
{
}

